import { StyleSheet } from "react-native";
export const colors = {
  background: "#080d19",
  surface: "#141d30",
  border: "#394257",
  gold: "#efcf87",
  text: "#f7f0df",
  muted: "#b9c3d5",
  error: "#ffaaaa",
};
export const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.background },
  container: {
    width: "100%",
    maxWidth: 1180,
    alignSelf: "center",
    padding: 20,
    gap: 20,
  },
  panel: {
    backgroundColor: colors.surface,
    borderColor: colors.border,
    borderWidth: 1,
    borderRadius: 14,
    padding: 20,
    gap: 14,
  },
  row: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    gap: 12,
  },
  title: { fontSize: 34, fontWeight: "700", color: colors.text },
  heading: { fontSize: 24, fontWeight: "600", color: colors.gold },
  body: { fontSize: 16, lineHeight: 25, color: colors.text },
  muted: { fontSize: 14, lineHeight: 22, color: colors.muted },
  input: {
    backgroundColor: colors.background,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 8,
    color: colors.text,
    padding: 12,
    fontSize: 16,
    minHeight: 46,
  },
  button: {
    backgroundColor: colors.gold,
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 17,
    minHeight: 46,
    justifyContent: "center",
  },
  buttonText: { color: colors.background, fontSize: 16, fontWeight: "600" },
  secondary: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  secondaryText: { color: colors.gold },
  error: { color: colors.error, fontSize: 16 },
  image: { width: "100%", height: 300 },
  link: { color: colors.gold, fontSize: 16, textDecorationLine: "underline" },
});
